version: '3.4'

services:
  identitydb:
    container_name: identitydb
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=YourStrongPassword!
    restart: always
    ports:
       - "1433:1433"

  identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"
  
       